-- GENERATED by scripts/platform/render-seed.ts from lib/governance/catalog.ts (PERMISSIONS_V2, GRANTS_V2). Do not edit by hand.
-- Governance changes after the first release: new permissions, roles and grants (inserted only when missing),
-- and least-privilege revocations of seeded defaults (seeded rows only; grants added by administrators are kept).

INSERT INTO roles (id, key, name, description, rank, is_protected, max_holders) VALUES ('role:developer', 'developer', 'Developer', 'Website developers. Holds no permissions by default: governance administrators grant exactly what the work needs.', 20, 0, NULL) ON CONFLICT(id) DO NOTHING;
UPDATE roles SET name = 'Technical Administrator', description = 'Technical administration: media library, forms, settings and read access for support. Does not approve members or carry Moderator authority unless explicitly granted.' WHERE id = 'role:administrator' AND updated_by IS NULL;
DELETE FROM role_permissions WHERE role_id = 'role:administrator' AND permission_id = 'perm:members.approve' AND scope = 'ALL' AND scope_value = '' AND created_by IS NULL;
DELETE FROM role_permissions WHERE role_id = 'role:administrator' AND permission_id = 'perm:members.reject' AND scope = 'ALL' AND scope_value = '' AND created_by IS NULL;
DELETE FROM role_permissions WHERE role_id = 'role:administrator' AND permission_id = 'perm:members.manage' AND scope = 'ALL' AND scope_value = '' AND created_by IS NULL;
DELETE FROM role_permissions WHERE role_id = 'role:administrator' AND permission_id = 'perm:users.create' AND scope = 'ALL' AND scope_value = '' AND created_by IS NULL;
DELETE FROM role_permissions WHERE role_id = 'role:administrator' AND permission_id = 'perm:users.update' AND scope = 'ALL' AND scope_value = '' AND created_by IS NULL;
DELETE FROM role_permissions WHERE role_id = 'role:administrator' AND permission_id = 'perm:users.suspend' AND scope = 'ALL' AND scope_value = '' AND created_by IS NULL;
INSERT INTO permissions (id, key, resource, action, description, is_sensitive) VALUES ('perm:recruitment.manage', 'recruitment.manage', 'recruitment', 'manage', 'Run recruitment campaigns and review applications', 0) ON CONFLICT(id) DO NOTHING;
INSERT INTO permissions (id, key, resource, action, description, is_sensitive) VALUES ('perm:messages.read', 'messages.read', 'messages', 'read', 'Read and handle contact-form messages', 0) ON CONFLICT(id) DO NOTHING;
INSERT INTO position_permissions (position_id, permission_id, scope, scope_value) VALUES ('pos:president', 'perm:recruitment.manage', 'ALL', '') ON CONFLICT(position_id, permission_id, scope, scope_value) DO NOTHING;
INSERT INTO position_permissions (position_id, permission_id, scope, scope_value) VALUES ('pos:president', 'perm:messages.read', 'ALL', '') ON CONFLICT(position_id, permission_id, scope, scope_value) DO NOTHING;
INSERT INTO position_permissions (position_id, permission_id, scope, scope_value) VALUES ('pos:general-secretary', 'perm:recruitment.manage', 'ALL', '') ON CONFLICT(position_id, permission_id, scope, scope_value) DO NOTHING;
INSERT INTO position_permissions (position_id, permission_id, scope, scope_value) VALUES ('pos:general-secretary', 'perm:messages.read', 'ALL', '') ON CONFLICT(position_id, permission_id, scope, scope_value) DO NOTHING;
INSERT INTO position_permissions (position_id, permission_id, scope, scope_value) VALUES ('pos:information-secretary', 'perm:messages.read', 'ALL', '') ON CONFLICT(position_id, permission_id, scope, scope_value) DO NOTHING;
INSERT INTO position_permissions (position_id, permission_id, scope, scope_value) VALUES ('pos:event-coordinator', 'perm:events.create', 'ALL', '') ON CONFLICT(position_id, permission_id, scope, scope_value) DO NOTHING;
INSERT INTO position_permissions (position_id, permission_id, scope, scope_value) VALUES ('pos:event-coordinator', 'perm:events.update', 'OWN', '') ON CONFLICT(position_id, permission_id, scope, scope_value) DO NOTHING;
