#!/usr/bin/env bun
/**
 * Renders lib/governance/catalog.ts into migrations/0002_governance_seed.sql.
 *
 *   bun scripts/platform/render-seed.ts          write the file
 *   bun scripts/platform/render-seed.ts --check  fail if the file is stale (CI)
 *
 * The seed only inserts missing rows (ON CONFLICT DO NOTHING), so it never
 * overwrites what administrators have since changed in the database.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { APPROVAL_POLICIES, GRANTS_V2, GRANTS_V3, GRANTS_V4, PERMISSIONS, PERMISSIONS_V2, PERMISSIONS_V3, PERMISSIONS_V4, POLICIES_V4, POSITIONS, POSITIONS_V3, PROTECTED_RULES_OPENED_V4, REVOKES_V2, RULE_TEXT_FIXES_V4, ROLE_RENAMES_V2, ROLES, ROLES_V2, ROLES_V4, RULE_TEMPLATES_V4, RULES, SYSTEM_SETTINGS, SYSTEM_SETTINGS_V4, splitTitles, type RuleDef } from "../../lib/governance/catalog";
import { insertSql } from "../../lib/migration/sql";

const out: string[] = [
  "-- GENERATED by scripts/platform/render-seed.ts from lib/governance/catalog.ts. Do not edit by hand.",
  "-- Default governance: permissions, roles, positions, approval policies, rules and settings.",
  "-- Inserts only missing rows; administrators' later changes are never overwritten.",
  "",
];
const add = (table: string, row: Record<string, unknown>, conflict?: string[]) =>
  out.push(insertSql(table, row as never, { conflict, mode: "nothing" }));

out.push("-- permissions");
for (const p of PERMISSIONS) {
  const [resource, action] = p.key === "*" ? ["*", "*"] : p.key.split(".");
  add("permissions", { id: `perm:${p.key}`, key: p.key, resource, action, description: p.description, is_sensitive: p.sensitive ? 1 : 0 });
}

out.push("", "-- roles and their grants");
for (const r of ROLES) {
  add("roles", { id: `role:${r.key}`, key: r.key, name: r.name, description: r.description, rank: r.rank, is_protected: r.isProtected ? 1 : 0, max_holders: r.maxHolders ?? null });
  for (const g of r.grants) {
    add("role_permissions", { role_id: `role:${r.key}`, permission_id: `perm:${g.permission}`, scope: g.scope ?? "ALL", scope_value: g.scopeValue ?? "" },
      ["role_id", "permission_id", "scope", "scope_value"]);
  }
}

out.push("", "-- positions (parents first) and their default grants");
const byKey = new Map(POSITIONS.map((p) => [p.key, p]));
const ordered = [...POSITIONS].sort((a, b) => Number(Boolean(a.parent)) - Number(Boolean(b.parent)) || a.rank - b.rank);
for (const p of ordered) {
  if (p.parent && !byKey.has(p.parent)) throw new Error(`Position ${p.key} has unknown parent ${p.parent}`);
  add("positions", {
    id: `pos:${p.key}`, key: p.key, name: p.name, description: p.description ?? null, category: p.category, rank: p.rank,
    parent_id: p.parent ? `pos:${p.parent}` : null, display_order: p.rank, is_active: 1, is_protected: p.isProtected ? 1 : 0,
    max_holders: p.maxHolders ?? null, aliases_json: { aliases: p.aliases ?? [], pattern: p.aliasPattern ?? null },
  });
  for (const g of p.grants ?? []) {
    add("position_permissions", { position_id: `pos:${p.key}`, permission_id: `perm:${g.permission}`, scope: g.scope ?? "ALL", scope_value: g.scopeValue ?? "" },
      ["position_id", "permission_id", "scope", "scope_value"]);
  }
}

out.push("", "-- approval policies");
for (const p of APPROVAL_POLICIES) {
  add("approval_policies", { id: `policy:${p.key}`, key: p.key, name: p.name, description: p.description, mode: p.mode, threshold: p.threshold ?? null,
    approvers_json: p.approvers, allow_self_approval: 0, is_protected: p.isProtected ? 1 : 0 });
}

out.push("", "-- governance rules");
for (const r of RULES) {
  add("rules", { id: `rule:${r.key}`, key: r.key, name: r.name, description: r.description, trigger: "AUTHORIZE", permission_key: r.permission,
    resource_type: r.resourceType ?? null, scope: r.scope ?? "ALL", scope_value: r.scopeValue ?? "", priority: r.priority,
    approval_policy_id: r.approvalPolicy ? `policy:${r.approvalPolicy}` : null, is_protected: r.isProtected ? 1 : 0, status: "ACTIVE",
    activated_at: "2026-09-25T00:00:00.000Z" });
  add("rule_actions", { id: `rule:${r.key}:action:0`, rule_id: `rule:${r.key}`, action_type: r.effect,
    params_json: r.approvalPolicy ? { policy: r.approvalPolicy } : null, sort_order: 0 });
  r.conditions.forEach((c, i) =>
    add("rule_conditions", { id: `rule:${r.key}:cond:${i}`, rule_id: `rule:${r.key}`, group_no: c.group ?? 0, field: c.field, operator: c.operator,
      value_json: c.value === undefined ? null : JSON.stringify(c.value), sort_order: i }),
  );
}

out.push("", "-- system settings");
for (const s of SYSTEM_SETTINGS) {
  add("system_settings", { key: s.key, value_json: JSON.stringify(s.value), is_protected: s.isProtected ? 1 : 0, description: s.description }, ["key"]);
}

const sql = `${out.join("\n")}\n`;

// ── v2 additions ──
const v2: string[] = [
  "-- GENERATED by scripts/platform/render-seed.ts from lib/governance/catalog.ts (PERMISSIONS_V2, GRANTS_V2). Do not edit by hand.",
  "-- Governance changes after the first release: new permissions, roles and grants (inserted only when missing),",
  "-- and least-privilege revocations of seeded defaults (seeded rows only; grants added by administrators are kept).",
  "",
];
const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
for (const r of ROLES_V2) {
  v2.push(insertSql("roles", { id: `role:${r.key}`, key: r.key, name: r.name, description: r.description, rank: r.rank, is_protected: 0, max_holders: null } as never, { mode: "nothing" }));
}
for (const r of ROLE_RENAMES_V2) {
  v2.push(`UPDATE roles SET name = ${q(r.name)}, description = ${q(r.description)} WHERE id = ${q(`role:${r.key}`)} AND updated_by IS NULL;`);
}
for (const g of REVOKES_V2) {
  v2.push(`DELETE FROM role_permissions WHERE role_id = ${q(`role:${g.role}`)} AND permission_id = ${q(`perm:${g.permission}`)} AND scope = ${q(g.scope ?? "ALL")} AND scope_value = ${q(g.scopeValue ?? "")} AND created_by IS NULL;`);
}
for (const p of PERMISSIONS_V2) {
  const [resource, action] = p.key.split(".");
  v2.push(insertSql("permissions", { id: `perm:${p.key}`, key: p.key, resource, action, description: p.description, is_sensitive: p.sensitive ? 1 : 0 } as never, { mode: "nothing" }));
}
for (const g of GRANTS_V2) {
  if (g.role) v2.push(insertSql("role_permissions", { role_id: `role:${g.role}`, permission_id: `perm:${g.permission}`, scope: g.scope ?? "ALL", scope_value: g.scopeValue ?? "" } as never, { conflict: ["role_id", "permission_id", "scope", "scope_value"], mode: "nothing" }));
  if (g.position) v2.push(insertSql("position_permissions", { position_id: `pos:${g.position}`, permission_id: `perm:${g.permission}`, scope: g.scope ?? "ALL", scope_value: g.scopeValue ?? "" } as never, { conflict: ["position_id", "permission_id", "scope", "scope_value"], mode: "nothing" }));
}
const sqlV2 = `${v2.join("\n")}\n`;

// ── v3 additions ──
const v3: string[] = [
  "-- GENERATED by scripts/platform/render-seed.ts from lib/governance/catalog.ts (PERMISSIONS_V3, GRANTS_V3, POSITIONS_V3). Do not edit by hand.",
  "-- Positions of the 2026 structure split out of broader ones: each is inserted when missing, starts with the grants its",
  "-- origin position has in this database, takes over its exact titles, and existing assignments with those titles move",
  "-- to it (display titles are unchanged). Plus permissions for bulk executive import and admin-issued password resets.",
  "",
];
for (const p of PERMISSIONS_V3) {
  const [resource, action] = p.key.split(".");
  v3.push(insertSql("permissions", { id: `perm:${p.key}`, key: p.key, resource, action, description: p.description, is_sensitive: p.sensitive ? 1 : 0 } as never, { mode: "nothing" }));
}
for (const p of POSITIONS_V3) {
  const titles = splitTitles(p);
  const lowered = titles.map((t) => q(t.toLowerCase())).join(", ");
  v3.push(insertSql("positions", {
    id: `pos:${p.key}`, key: p.key, name: p.name, description: p.description ?? null, category: p.category, rank: p.rank,
    parent_id: p.parent ? `pos:${p.parent}` : null, display_order: p.rank, is_active: 1, is_protected: p.isProtected ? 1 : 0,
    max_holders: p.maxHolders ?? null, aliases_json: { aliases: p.aliases ?? [], pattern: null },
  } as never, { mode: "nothing" }));
  v3.push(`INSERT OR IGNORE INTO position_permissions (position_id, permission_id, scope, scope_value) SELECT ${q(`pos:${p.key}`)}, permission_id, scope, scope_value FROM position_permissions WHERE position_id = ${q(`pos:${p.from}`)};`);
  v3.push(`UPDATE positions SET aliases_json = json_object('aliases', json((SELECT json_group_array(value) FROM json_each(positions.aliases_json, '$.aliases') WHERE lower(value) NOT IN (${lowered}))), 'pattern', json_extract(aliases_json, '$.pattern')) WHERE id = ${q(`pos:${p.from}`)};`);
  v3.push(`UPDATE committee_members SET position_id = ${q(`pos:${p.key}`)} WHERE position_id = ${q(`pos:${p.from}`)} AND lower(trim(position_title)) IN (${lowered});`);
}
for (const g of GRANTS_V3) {
  if (g.role) v3.push(insertSql("role_permissions", { role_id: `role:${g.role}`, permission_id: `perm:${g.permission}`, scope: g.scope ?? "ALL", scope_value: g.scopeValue ?? "" } as never, { conflict: ["role_id", "permission_id", "scope", "scope_value"], mode: "nothing" }));
  if (g.position) v3.push(insertSql("position_permissions", { position_id: `pos:${g.position}`, permission_id: `perm:${g.permission}`, scope: g.scope ?? "ALL", scope_value: g.scopeValue ?? "" } as never, { conflict: ["position_id", "permission_id", "scope", "scope_value"], mode: "nothing" }));
}
const sqlV3 = `${v3.join("\n")}\n`;

// ── v4 additions ──
const v4: string[] = [
  "-- GENERATED by scripts/platform/render-seed.ts from lib/governance/catalog.ts (PERMISSIONS_V4, GRANTS_V4, POLICIES_V4,",
  "-- RULE_TEMPLATES_V4, SYSTEM_SETTINGS_V4). Do not edit by hand.",
  "-- The President and General Secretary share governance powers (roles, positions, grants), bounded by the invariants and,",
  "-- for sensitive permissions, a Moderator's approval. Every executive may post events and posts of their own. Messaging",
  "-- permissions, the sensitive-grant policy, inactive auto-publish rule templates, and security settings.",
  "",
];
for (const p of PERMISSIONS_V4) {
  const [resource, action] = p.key.split(".");
  v4.push(insertSql("permissions", { id: `perm:${p.key}`, key: p.key, resource, action, description: p.description, is_sensitive: p.sensitive ? 1 : 0 } as never, { mode: "nothing" }));
}
for (const r of ROLES_V4) {
  v4.push(insertSql("roles", { id: `role:${r.key}`, key: r.key, name: r.name, description: r.description, rank: r.rank, is_protected: 0, max_holders: null } as never, { mode: "nothing" }));
  for (const g of r.grants) {
    v4.push(insertSql("role_permissions", { role_id: `role:${r.key}`, permission_id: `perm:${g.permission}`, scope: g.scope ?? "ALL", scope_value: g.scopeValue ?? "" } as never,
      { conflict: ["role_id", "permission_id", "scope", "scope_value"], mode: "nothing" }));
  }
}
for (const g of GRANTS_V4) {
  if (g.role) v4.push(insertSql("role_permissions", { role_id: `role:${g.role}`, permission_id: `perm:${g.permission}`, scope: g.scope ?? "ALL", scope_value: g.scopeValue ?? "" } as never, { conflict: ["role_id", "permission_id", "scope", "scope_value"], mode: "nothing" }));
  if (g.position) v4.push(insertSql("position_permissions", { position_id: `pos:${g.position}`, permission_id: `perm:${g.permission}`, scope: g.scope ?? "ALL", scope_value: g.scopeValue ?? "" } as never, { conflict: ["position_id", "permission_id", "scope", "scope_value"], mode: "nothing" }));
}
// The protected DENY rules for these powers keep applying to everyone else.
for (const permission of PROTECTED_RULES_OPENED_V4) {
  const ruleId = `rule:protected-${permission.replace(".", "-")}`;
  v4.push(insertSql("rule_conditions", { id: `${ruleId}:cond:1`, rule_id: ruleId, group_no: 0, field: "actor.position", operator: "not_in",
    value_json: JSON.stringify(["president", "general-secretary"]), sort_order: 1 } as never, { mode: "nothing" }));
  v4.push(`UPDATE rules SET description = ${q("Protected: only Moderators, the President and the General Secretary; prevents privilege escalation through role, permission and policy changes.")}, name = ${q(`${permission} is leadership-only`)} WHERE id = ${q(ruleId)} AND updated_by IS NULL;`);
}
for (const p of POLICIES_V4) {
  v4.push(insertSql("approval_policies", { id: `policy:${p.key}`, key: p.key, name: p.name, description: p.description, mode: p.mode, threshold: p.threshold ?? null,
    approvers_json: p.approvers, allow_self_approval: 0, is_protected: p.isProtected ? 1 : 0 } as never, { mode: "nothing" }));
}
const ruleRows = (r: RuleDef, status: string, sink: string[]) => {
  sink.push(insertSql("rules", { id: `rule:${r.key}`, key: r.key, name: r.name, description: r.description, trigger: "AUTHORIZE", permission_key: r.permission,
    resource_type: r.resourceType ?? null, scope: r.scope ?? "ALL", scope_value: r.scopeValue ?? "", priority: r.priority,
    approval_policy_id: r.approvalPolicy ? `policy:${r.approvalPolicy}` : null, is_protected: r.isProtected ? 1 : 0, status } as never, { mode: "nothing" }));
  sink.push(insertSql("rule_actions", { id: `rule:${r.key}:action:0`, rule_id: `rule:${r.key}`, action_type: r.effect,
    params_json: r.approvalPolicy ? { policy: r.approvalPolicy } : null, sort_order: 0 } as never, { mode: "nothing" }));
  r.conditions.forEach((c, i) =>
    sink.push(insertSql("rule_conditions", { id: `rule:${r.key}:cond:${i}`, rule_id: `rule:${r.key}`, group_no: c.group ?? 0, field: c.field, operator: c.operator,
      value_json: c.value === undefined ? null : JSON.stringify(c.value), sort_order: i } as never, { mode: "nothing" })),
  );
};
for (const r of RULE_TEMPLATES_V4) ruleRows(r, "INACTIVE", v4);
for (const f of RULE_TEXT_FIXES_V4) v4.push(`UPDATE rules SET description = ${q(f.description)} WHERE key = ${q(f.key)} AND updated_by IS NULL;`);
for (const s of SYSTEM_SETTINGS_V4) {
  v4.push(insertSql("system_settings", { key: s.key, value_json: JSON.stringify(s.value), is_protected: s.isProtected ? 1 : 0, description: s.description } as never, { conflict: ["key"], mode: "nothing" }));
}
const sqlV4 = `${v4.join("\n")}\n`;

const files: Array<[string, string]> = [
  [path.join(process.cwd(), "migrations", "0002_governance_seed.sql"), sql],
  [path.join(process.cwd(), "migrations", "0004_governance_seed_v2.sql"), sqlV2],
  [path.join(process.cwd(), "migrations", "0006_governance_seed_v3.sql"), sqlV3],
  [path.join(process.cwd(), "migrations", "0008_governance_seed_v4.sql"), sqlV4],
];
if (process.argv.includes("--check")) {
  const stale = files.filter(([f, content]) => !existsSync(f) || readFileSync(f, "utf8") !== content);
  if (stale.length) {
    console.error(`Stale seed migration(s): ${stale.map(([f]) => path.basename(f)).join(", ")}. Run: bun scripts/platform/render-seed.ts`);
    process.exit(1);
  }
  console.log("Seed migrations are up to date.");
} else {
  for (const [f, content] of files) writeFileSync(f, content);
  console.log(`Wrote ${files.map(([f]) => path.basename(f)).join(", ")}.`);
}
