export interface Contributor {
  login: string;
  name: string;
  avatar_url: string;
  html_url: string;
  /** Commits. */
  contributions: number;
  /** Commits that changed at least 10 authored lines (the ones the ranking counts). */
  realCommits?: number;
  /** Lines added and deleted in authored files (when the ranking was computed from history). */
  additions?: number;
  deletions?: number;
  /** Fair-ranking score, 0–100 (lib/contributors/score.ts). */
  score?: number;
}

/**
 * GUCC contributors in the site's fair order (75% lines of code (additions + half of deletions) and 25% real commits (10+ lines each), square-root scaled; generated files excluded).
 * Generated by scripts/platform/contributors.ts --write-static from the full git history; bots excluded.
 */
export const STATIC_CONTRIBUTORS: Contributor[] = [
  {
    "login": "BakulBd",
    "name": "Bakul Ahmed",
    "avatar_url": "https://avatars.githubusercontent.com/u/143816025?v=4",
    "html_url": "https://github.com/BakulBd",
    "contributions": 81,
    "realCommits": 54,
    "additions": 26442,
    "deletions": 7149,
    "score": 100
  },
  {
    "login": "nurulhudaapon",
    "name": "Nurul Huda (Apon)",
    "avatar_url": "https://avatars.githubusercontent.com/u/55424194?v=4",
    "html_url": "https://github.com/nurulhudaapon",
    "contributions": 74,
    "realCommits": 40,
    "additions": 10731,
    "deletions": 2848,
    "score": 69.2
  },
  {
    "login": "imranonweb",
    "name": "Al Imran Emon",
    "avatar_url": "https://avatars.githubusercontent.com/u/138112368?v=4",
    "html_url": "https://github.com/imranonweb",
    "contributions": 28,
    "realCommits": 22,
    "additions": 4436,
    "deletions": 2726,
    "score": 48.9
  },
  {
    "login": "ShahJahanApurbo",
    "name": "Md Shajahan Apurba",
    "avatar_url": "https://avatars.githubusercontent.com/u/102844859?v=4",
    "html_url": "https://github.com/ShahJahanApurbo",
    "contributions": 3,
    "realCommits": 3,
    "additions": 3262,
    "deletions": 21,
    "score": 30.7
  },
  {
    "login": "MrMajharul",
    "name": "Majharul Islam",
    "avatar_url": "https://avatars.githubusercontent.com/u/158082213?v=4",
    "html_url": "https://github.com/MrMajharul",
    "contributions": 24,
    "realCommits": 9,
    "additions": 2111,
    "deletions": 76,
    "score": 30.3
  },
  {
    "login": "jawadhossainmahi",
    "name": "Jawad Hossain Mahi",
    "avatar_url": "https://avatars.githubusercontent.com/u/100514487?v=4",
    "html_url": "https://github.com/jawadhossainmahi",
    "contributions": 24,
    "realCommits": 9,
    "additions": 1412,
    "deletions": 409,
    "score": 27.6
  },
  {
    "login": "zahinafsar",
    "name": "Zahin Afsar",
    "avatar_url": "https://avatars.githubusercontent.com/u/43959210?v=4",
    "html_url": "https://github.com/zahinafsar",
    "contributions": 3,
    "realCommits": 3,
    "additions": 1457,
    "deletions": 820,
    "score": 24.6
  },
  {
    "login": "itshimelz",
    "name": "Rahat Hossain Himel",
    "avatar_url": "https://avatars.githubusercontent.com/u/51039076?v=4",
    "html_url": "https://github.com/itshimelz",
    "contributions": 5,
    "realCommits": 5,
    "additions": 625,
    "deletions": 340,
    "score": 19.8
  },
  {
    "login": "imtiazahmadtanvir",
    "name": "Imtiaz Ahmad Tanvir",
    "avatar_url": "https://avatars.githubusercontent.com/u/169084828?v=4",
    "html_url": "https://github.com/imtiazahmadtanvir",
    "contributions": 2,
    "realCommits": 2,
    "additions": 1088,
    "deletions": 151,
    "score": 19.6
  },
  {
    "login": "ammarbinanwarfuad",
    "name": "Ammar Bin Anwar Fuad",
    "avatar_url": "https://avatars.githubusercontent.com/u/71203673?v=4",
    "html_url": "https://github.com/ammarbinanwarfuad",
    "contributions": 2,
    "realCommits": 1,
    "additions": 806,
    "deletions": 1,
    "score": 15.7
  },
  {
    "login": "ShipluSaha995",
    "name": "Shiplu Saha",
    "avatar_url": "https://avatars.githubusercontent.com/u/182983099?v=4",
    "html_url": "https://github.com/ShipluSaha995",
    "contributions": 13,
    "realCommits": 4,
    "additions": 346,
    "deletions": 76,
    "score": 15.3
  },
  {
    "login": "Arafahmed1314",
    "name": "Naimul Islam",
    "avatar_url": "https://avatars.githubusercontent.com/u/112814299?v=4",
    "html_url": "https://github.com/Arafahmed1314",
    "contributions": 1,
    "realCommits": 1,
    "additions": 553,
    "deletions": 43,
    "score": 13.8
  },
  {
    "login": "idontbyte69",
    "name": "idontbyte69",
    "avatar_url": "https://avatars.githubusercontent.com/u/118148681?v=4",
    "html_url": "https://github.com/idontbyte69",
    "contributions": 10,
    "realCommits": 3,
    "additions": 292,
    "deletions": 18,
    "score": 13.4
  },
  {
    "login": "srtanveer",
    "name": "MD Showaib Rahman Tanveer",
    "avatar_url": "https://avatars.githubusercontent.com/u/118148681?v=4",
    "html_url": "https://github.com/srtanveer",
    "contributions": 2,
    "realCommits": 1,
    "additions": 436,
    "deletions": 0,
    "score": 12.4
  },
  {
    "login": "Andrew-Velox",
    "name": "Mohabbat Marjuk Muttaki",
    "avatar_url": "https://avatars.githubusercontent.com/u/99073463?v=4",
    "html_url": "https://github.com/Andrew-Velox",
    "contributions": 7,
    "realCommits": 2,
    "additions": 188,
    "deletions": 79,
    "score": 11.3
  },
  {
    "login": "naimulhasannabil",
    "name": "Naimul Hasan Nabil",
    "avatar_url": "https://avatars.githubusercontent.com/u/147473435?v=4",
    "html_url": "https://github.com/naimulhasannabil",
    "contributions": 1,
    "realCommits": 1,
    "additions": 55,
    "deletions": 11,
    "score": 6.8
  },
  {
    "login": "nupur221",
    "name": "nupur221",
    "avatar_url": "https://avatars.githubusercontent.com/u/146472606?v=4",
    "html_url": "https://github.com/nupur221",
    "contributions": 2,
    "realCommits": 1,
    "additions": 32,
    "deletions": 9,
    "score": 6
  },
  {
    "login": "mahmudaakternadia",
    "name": "Mahmuda Akter Nadia",
    "avatar_url": "https://avatars.githubusercontent.com/u/116658441?v=4",
    "html_url": "https://github.com/mahmudaakternadia",
    "contributions": 5,
    "realCommits": 1,
    "additions": 4,
    "deletions": 50,
    "score": 5.7
  },
  {
    "login": "Sajjad-Mahmud-Suton",
    "name": "MD. Sajjad Mahmud Suton",
    "avatar_url": "https://avatars.githubusercontent.com/u/152319548?v=4",
    "html_url": "https://github.com/Sajjad-Mahmud-Suton",
    "contributions": 5,
    "realCommits": 0,
    "additions": 0,
    "deletions": 0,
    "score": 0
  },
  {
    "login": "thimel07",
    "name": "Tasnimul Hasan Himel",
    "avatar_url": "https://avatars.githubusercontent.com/u/211148768?v=4",
    "html_url": "https://github.com/thimel07",
    "contributions": 1,
    "realCommits": 0,
    "additions": 0,
    "deletions": 0,
    "score": 0
  }
];
